create database drink;
use drink;
create table SOFTDRINK(
DRINKCODE INT,
DNAME CHAR(30),
PRICE float,
CALORIES int);
INSERT INTO SOFTDRINK 
VALUES
(101,"Lime and Lemon",20.00,120),
(102,"Apple Drink",18.00,120),
(103,"Nature Necture",15.00,115),
(104,"Green Mango",15.00,140),
(105,"Aam Panna",20.00,135),
(106,"MAngo Juice Bahar",12.00,140);
select * from SOFTDRINK;

#QUESTION 1
SELECT DNAME,DRINKCODE FROM SOFTDRINK
WHERE CALORIES >120;

#QUESTION 2
SELECT DRINKCODE,DNAME,CALORIES FROM SOFTDRINK
ORDER BY CALORIES DESC;

#QUESTION 3

SELECT DNAME,PRICE FROM SOFTDRINK
WHERE PRICE  BETWEEN 12 AND 18;

#QUESTION 4


update SOFTDRINK
    set PRICE = PRICE + (PRICE * 10/100);
    
SET SQL_SAFE_UPDATES=0;

#QUESTION 5

INSERT INTO SOFTDRINK VALUES(108,"Orange Juice",14.00,120);

#QUESTION 6

DELETE FROM SOFTDRINK
WHERE DRINKCODE = 102;

#QUESTION 7

SELECT COUNT(DISTINCT(PRICE)) FROM SOFTDRINK;

#QUESTION 8

SELECT MAX(CALORIES) FROM SOFTDRINK;


#9c
SELECT DNAME FROM SOFTDRINK 
WHERE DNAME  LIKE "%Mango%";
